version: "1.0"
services:
  gpt_lit:
    image: node:18-alpine
    container_name: gpt_lit
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
    command: npm run dev
